/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries
SELECT country,
	   COUNT(customer_key) AS total_customer 
FROM   customers
GROUP BY country;
  

-- Find total customers by gender

SELECT gender,
	   COUNT(customer_key) AS total_customer 
FROM   customers
GROUP BY gender;

-- Find total products by category
SELECT 
		category, 
        COUNT(product_key) AS total_products
FROM 	products
GROUP BY category;


-- What is the average costs in each category?
SELECT 
		category, 
        AVG(cost) AS avg_cost
FROM 	products
GROUP BY category;

-- What is the total revenue generated for each category?
SELECt 
		 p.category,
         SUM(s.quantity*s.price) AS revenue_generated 
FROM 	 products p INNER JOIN sales s 
ON 		 p.product_key=s.product_key
GROUP BY p.category;

-- What is the total revenue generated by each customer?
SELECt 
		 c.customer_key AS customer_key,
         CONCAT(c.first_name, " ",c.last_name) AS customer_name,
         SUM(s.quantity*s.price) AS revenue_generated 
FROM 	 customers c INNER JOIN sales s 
ON 		 c.customer_key=s.customer_key
GROUP BY customer_key,customer_name
ORDER BY revenue_generated DESC;


-- What is the distribution of sold items across countries?

SELECT 
		 c.country,
		 SUM(s.quantity) AS Total_distribution 
FROM 	 customers c INNER JOIN sales s 
ON 		 c.customer_key = s.customer_key
GROUP BY c.country;


